### PR TITLE
Feat/deconstruct index

### PR DESCRIPTION
**Pull request by LimitedHype**
- Added Multi-Select Inputs (WIP don't use yet)
- Decoupled logic in index.ts to its own dir structure
- Parameterized some functions for QoL in near future (adding case)
- Other stuff

### CODE REVIEW

**Comment by kamath** [comment]
what is `slash-command`? use `barbell/`

**Comment by LimitedHype** [comment]
> what is `slash-command`? use `barbell/`

branch I was working off of had logic in slash-command. Gonna need to move that shii over

**Review by kamath — CHANGES_REQUESTED** [review]
pls move into `barbell/` 🙏 🙇

**Review by kamath — APPROVED** [review]
lgtm, my understanding is you'll follow up with another PR to fully move over `slash-command/` into `barbell/`

**Pull request merged**
